name: HTML Demo Automation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Display Success Message
      run: echo "HTML Project Checked Successfully!"
